Repository aukletio/Auklet-Agent-Python, pull requests merged in 2018-11, with the labels that each got.

#2 Bumping requests package version
  requirements.txt
Labels: bug

#5 Fix release logic
  .circleci/config.yml
  .devops/deploy.sh
Labels: devops

#7 Do not render changelogs at/below tag 1.0.1
  .devops/calculateChangelogs.js
  .devops/post-release.sh
  .devops/tests.sh
Labels: devops

#6 Release Candidate Review
  .circleci/config.yml
  .devops/calculateChangelogs.js
  .devops/deploy.sh
  .devops/post-release.sh
  .devops/tests.sh
Labels: release

#8 Drop defunct PR validation scripts
  .devops/validate-pr.sh
  .devops/validatePr.js
Labels: devops

#9 Pass Correct Context to MQTT Constructor
  auklet/broker.py
  tests/test_broker.py
Labels: bug

#10 Release Candidate Review
  .devops/validate-pr.sh
  .devops/validatePr.js
  auklet/broker.py
  tests/test_broker.py
Labels: release

#11 Release Review
  .devops/validate-pr.sh
  .devops/validatePr.js
  auklet/broker.py
  tests/test_broker.py
Labels: release

#12 Update instructions for bug reports
  README.md
Labels: devops

#15 Fixing Code Climate Links
  README.md
Labels: bug

#16 Release Candidate Review
  README.md
Labels: release

#14 Release Review
  README.md
Labels: release

#17 APM-1690: Deploy all branches to PyPI
  .devops/deploy.sh
Labels: enhancement
